export const GET_FILMS = 'GET_FILMS';
export const GET_CINEPLEX = 'GET_CINEPLEX';
export const GET_CINEPLEX_BY_ID = 'GET_CINEPLEX_BY_ID';
export const GET_CINEPLEX_BY_FILM_ID = 'GET_CINEPLEX_BY_FILM_ID';
export const GET_LIST_CINEPLEX_GROUP = 'GET_LIST_CINEPLEX_GROUP';
